[project]
name = "wall-heating-replacing-radiators"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]

[tool.ruff]
target-version = "py312"
lint.select = [
  "A",
  "ASYNC",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "D",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "I",
  "ICN",
  "INT",
  "ISC",
  "LOG",
  "N",
  "PGH",
  "PIE",
  "PT",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "TCH",
  "TID",
  "UP",
  "W",
  "YTT",
]
lint.ignore = [
  "N806",
  "B008",
  "B028",
  "B905",
  "COM812",
  "D100",
  "D103",
  "D104",
  "D107",
  "D211",
  "D212",
  "ERA001",
  "F821",
  "F841",
  "ISC001",
  "S101",
  "S301",
  "S311",
  "S603",
  "S605",
  "S607",
  "TC003",
  "W293",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = false